### ISSUE TITLE
iPhone X 12.1.2 Chimera

### ISSUE THREAD

**Issue by benmuu** [ConorTheDev/LyricifyBugTracker#10] opened 2020-01-15 10:53 UTC
Always crashes 
![D59B7FA5-F769-43D6-B975-48FC10476FB5](https://user-images.githubusercontent.com/59917033/72428231-362b0f80-37c8-11ea-8c4d-6b7200850e56.png)

**Comment by ConorTheDev** [comment] 2020-01-16 23:11
Duplicate of #12

**Closed by ConorTheDev** 2020-01-16 23:11 UTC
