### ISSUE TITLE
Lyricify crash ios 12.1

### ISSUE THREAD

**Issue by mesc101** [ConorTheDev/LyricifyBugTracker#9] opened 2020-01-15 06:38 UTC
Downloaded the app from packix and the spirngboard will not load up after install

**Comment by ConorTheDev** [comment] 2020-01-15 11:51
Can you please attach a crash log?

**Comment by ConorTheDev** [comment] 2020-01-16 23:12
Duplicate of #12

**Closed by ConorTheDev** 2020-01-16 23:12 UTC
